list: $/synoptica/order/models/payment/columns.yaml
modelClass: Synoptica\Order\Models\Payment
title: Payments
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'synoptica/order/payments/update/:id'
