title: Statuses
modelClass: Synoptica\Order\Models\Status
list: $/synoptica/order/models/status/columns.yaml
recordUrl: 'synoptica/order/statuses/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
